
@echo off
cls 
SET OLDPATH=%PATH%
call config.cmd


SET T=%OS%-%ARCH%
SET BUILD_TYPE=%B%
echo.
echo -----------------------------------------------------
echo    Building for %OS%, %ARCH%, %BUILD_TYPE% ...
echo -----------------------------------------------------
echo    Using    %TOOL_NAME%
echo -----------------------------------------------------
echo.    

SET CMAKE_ARGS=
rem SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_C_COMPILER=%CMAKE_CC% 
rem SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_CXX_COMPILER=%CMAKE_CXX% 

SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_C_COMPILER=%TOOLCHAIN_BIN%/%CMAKE_C_COMPILER%.exe 
SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_CXX_COMPILER=%TOOLCHAIN_BIN%/%CMAKE_CXX_COMPILER%.exe 
SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_MAKE_PROGRAM=%TOOLCHAIN_BIN%/%CMAKE_MAKE%.exe

SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% 
rem SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_INSTALL_PREFIX=%BASE%\dependencies\mingw32\bin
SET CMAKE_ARGS=%CMAKE_ARGS% -DLLVM_DIR=%LLVM_DIR%
SET CMAKE_ARGS=%CMAKE_ARGS% -DJAVA_PATH=%JAVA_PATH%
rem SET CMAKE_ARGS=%CMAKE_ARGS% -DU_WINDOWS=YES
rem SET CMAKE_ARGS=%CMAKE_ARGS% -DU_MINGW=YES
rem SET CMAKE_ARGS=%CMAKE_ARGS% -D_WINSOCK2_H=YES
SET CMAKE_ARGS=%CMAKE_ARGS% -DOS=%OS% 
SET CMAKE_ARGS=%CMAKE_ARGS% -DARCH=%ARCH% 
SET CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
SET CMAKE_ARGS=%CMAKE_ARGS%  -G %MAKE_TYPE% 

mkdir %BASE%target\build\%T%
cd %BASE%target\build\%T%

cmake %CMAKE_ARGS% -Wno-dev "%BASE%"
SET PATH=%OLDPATH%
cd %BASE%