REM 
REM Configuration
REM 

SET MAKE_TYPE="MinGW Makefiles"
SET TOOL_NAME=10-mingw64-32

REM Using clang
REM SET CC=clang
REM SET CXX=clang++

REM 
REM Toolchain
REM 

SET LLVM_DEPS=C:\Apps\local
SET TOOLCHAIN_PATH=%LLVM_DEPS%\%TOOL_NAME%

SET PATH=%PATH%;%TOOLCHAIN_PATH%\bin
SET MAKE_BIN=%TOOLCHAIN_PATH%\bin\mingw32-make.exe

REM 
REM Libraries
REM 

REM PTHREADS using mingw32
rem SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%DEPS_BASE%\pthreads\include
rem SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%DEPS_BASE%\pthreads\include
rem SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;%DEPS_BASE%\pthreads\lib
