
REM 
REM Configuration
REM 

SET MAKE_TYPE="MinGW Makefiles"
SET TOOL_NAME=01-mingw-32
SET TOOL_PATH=%TOOL_NAME%
SET ARCH=x86

REM 
REM Toolchain
REM 

SET LLVM_DEPS=C:\Apps\local
SET TOOLCHAIN_PATH=%LLVM_DEPS%\%TOOL_PATH%

SET PATH=%PATH%;%TOOLCHAIN_PATH%\bin
SET MAKE_BIN=%TOOLCHAIN_PATH%\bin\make.exe

REM 
REM Libraries
REM 

REM SET C_INCLUDE_PATH=
REM SET CPLUS_INCLUDE_PATH=
REM SET LD_LIBRARY_PATH=

REM PTHREADS not included in mingw distribution
SET USE_EXTERNAL_PTHREAD=TRUE

REM PTHREADS not included
rem SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%DEPS_BASE%\pthread\include
rem SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%DEPS_BASE%\pthread\include
rem SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;%DEPS_BASE%\pthread\lib
