
REM 
REM ??
REM gcc

SET MAKE_TYPE="MinGW Makefiles"
SET TOOL_NAME=02-mingw-32
SET TOOL_PATH=%TOOL_NAME%
SET ARCH=x86

REM 
REM Toolchain
REM 
SET CMAKE_C_COMPILER=gcc
SET CMAKE_CXX_COMPILER=gcc
SET CMAKE_MAKE=make

rem SET TOOLCHAIN_BASE=C:\Apps\local
SET TOOLCHAIN_PATH=C:\Apps\local\%TOOL_PATH%
SET TOOLCHAIN_BIN=%TOOLCHAIN_PATH%\bin

SET PATH=%PATH%;%TOOLCHAIN_BIN%
SET MAKE_BIN=%TOOLCHAIN_BIN%\%CMAKE_MAKE%.exe

REM 
REM Libraries
REM 

REM SET C_INCLUDE_PATH=
REM SET CPLUS_INCLUDE_PATH=
REM SET LD_LIBRARY_PATH=

REM PTHREADS not included in mingw distribution
SET USE_EXTERNAL_PTHREAD=TRUE
rem SET LIB=pthread
rem SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%DEPS_BASE%\%LIB%\include
rem SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%DEPS_BASE%\%LIB%\include
rem SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;%DEPS_BASE%\%LIB%\lib

REM For llvm
SET LLVM_DIR=C:\Users\cran\Dropbox\docs\projects\github\temp\llvm-dist.2
rem SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%LIB%\include
rem SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%LIB%\include
rem SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;%LIB%\lib
