
REM  mingw-w64-dgn + mingw-w32
REM  llvm 3.3
REM  clang
REM  No pthred included

SET MAKE_TYPE="MinGW Makefiles"
SET TOOL_NAME=03-mingw-32
SET TOOL_PATH=01-mingw-32
SET ARCH=x86

REM 
REM Toolchain
REM 
SET CMAKE_C_COMPILER=clang
SET CMAKE_CXX_COMPILER=clang
SET CMAKE_MAKE=make

SET TOOLCHAIN_PATH=C:/Apps/local/%TOOL_PATH%
SET TOOLCHAIN_BIN=%TOOLCHAIN_PATH%/bin

rem SET CMAKE_TOOLCHAIN_BIN= 
REM SET PATH=%PATH%;%TOOLCHAIN_BIN%
SET MAKE_BIN=%TOOLCHAIN_BIN%\%CMAKE_MAKE%.exe

REM 
REM Libraries
REM Not used: included in cmakefile

REM SET C_INCLUDE_PATH=
REM SET CPLUS_INCLUDE_PATH=
REM SET LD_LIBRARY_PATH=

REM PTHREADS not included in mingw distribution
SET USE_EXTERNAL_PTHREAD=TRUE
REM SET LIB=pthread
REM SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%DEPS_BASE%\%LIB%\include
REM SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%DEPS_BASE%\%LIB%\include
REM SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;%DEPS_BASE%\%LIB%\lib

REM For llvm
SET LLVM_DIR=C:\Users\cran\Dropbox\docs\projects\github\robovm\temp\llvm-dist.2
rem SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%LIB%\include
rem SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%LIB%\include
rem SET LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;%LIB%\lib
